.PHONY: check test bench soak
check:
	test -z "$$(gofmt -l cmd internal)"
	go vet ./...
	go test ./...
	go test -race ./...
test:
	go test ./...
bench:
	go run ./cmd/snugbench -keys 10000 -dataset sessions
soak:
	go run -buildvcs=false ./cmd/snugsoak -duration "$${DURATION:-24h}" -keys "$${KEYS:-100000}"
