package engine

import ("errors";"time";"unsafe";"snugkv/internal/arena")
const hotListIdleFreeze=6*time.Second
type hotList struct{elements [][]byte;lastMutation int64}
func newHotList(e [][]byte)*hotList{h:=&hotList{elements:make([][]byte,0,len(e))};for _,v:=range e{h.elements=append(h.elements,append([]byte(nil),v...))};return h}
func(h *hotList) memoryBytes()uint64{if h==nil{return 0};n:=uint64(unsafe.Sizeof(*h))+uint64(cap(h.elements))*uint64(unsafe.Sizeof([]byte(nil)));for _,v:=range h.elements{n+=uint64(cap(v))};return n}
func(h *hotList) appendRight(v [][]byte){for _,x:=range v{h.elements=append(h.elements,append([]byte(nil),x...))}}
func(h *hotList) appendLeft(v [][]byte){n:=make([][]byte,0,len(h.elements)+len(v));for i:=len(v)-1;i>=0;i--{n=append(n,append([]byte(nil),v[i]...))};h.elements=append(n,h.elements...)}
func(h *hotList) pop(left bool,c int)[][]byte{if c>len(h.elements){c=len(h.elements)};out:=make([][]byte,c);if left{for i:=0;i<c;i++{out[i]=append([]byte(nil),h.elements[i]...)};h.elements=h.elements[c:]}else{for i:=0;i<c;i++{out[i]=append([]byte(nil),h.elements[len(h.elements)-1-i]...)};h.elements=h.elements[:len(h.elements)-c]};return out}
func(h *hotList) idle(now time.Time)bool{return h==nil||h.lastMutation==0||now.Sub(time.UnixMilli(h.lastMutation))>=hotListIdleFreeze}
func(h *hotList) packed()([]byte,error){return encodePackedList(h.elements)}
func(s *Store) accountHotListResize(a,b uint64){if a==b{return};s.memory.mu.Lock();if b>a{d:=b-a;s.memory.used+=d;s.memory.hotLists+=d}else{d:=a-b;s.memory.used-=d;s.memory.hotLists-=d};s.memory.mu.Unlock()}
func hotListSidecarBytes(sh *shard)uint64{if sh.metas==nil||sh.metas.hotLists==nil{return 0};return uint64(cap(sh.metas.hotLists))*uint64(unsafe.Sizeof((*hotList)(nil)))}
func(s *Store) thawHotListLocked(sh *shard,key string,e entry)(*hotList,bool,error){if e.isHotList(){h,_,ok:=sh.hotListForKey(key);if !ok||h==nil{return nil,false,errors.New("HOT list sidecar invariant")};return h,true,nil};if e.valueType!=TypeList{return nil,false,nil};if s.memory.max.Load()!=0{return nil,false,nil};data:=sh.encoded(e);var el [][]byte;var err error;if isIndexedList(data){el,err=decodeIndexedList(data)}else{el,err=decodePackedList(data)};if err!=nil{return nil,false,err};if len(el)<indexedListPromoteElements{return nil,false,nil};id,ok:=sh.data.Get(key);if !ok{return nil,false,nil};h:=newHotList(el);h.lastMutation=s.now().UnixMilli();hb:=h.memoryBytes();side:=uint64(0);if sh.metas==nil{side=uint64(unsafe.Sizeof(entryMetaSidecar{}))+uint64(cap(sh.entries))*entryMetaSlotBytes};oldCap:=0;if sh.metas!=nil{oldCap=cap(sh.metas.hotLists)};slots:=uint64(0);if cap(sh.entries)>oldCap{slots=uint64(cap(sh.entries)-oldCap)*uint64(unsafe.Sizeof((*hotList)(nil)))};oldPayload,oldBlock,free:=uint64(0),uint64(0),uint64(0);if !e.ref.IsInline(){oldPayload=uint64(len(data));oldBlock=sh.arena.AllocationBytes(e.ref);free=sh.arena.FreeGrowth(e.ref)};s.memory.mu.Lock();s.memory.used+=hb+slots+side+free;s.memory.hotLists+=hb+slots;s.memory.entries+=side;s.memory.arenas+=free;if oldPayload>0{s.memory.arenaPayload-=oldPayload};if oldBlock>0{s.memory.arenaLiveBlocks-=oldBlock};s.memory.mu.Unlock();if !e.ref.IsInline(){sh.arena.Free(e.ref)};e.rawStable=true;e.ref=arena.Ref{};sh.entries[id]=e.entryData;sh.setHotList(id,h);return h,true,nil}
func(s *Store) freezeHotListLocked(sh *shard,key string,e entry)error{if !e.isHotList(){return nil};h,_,ok:=sh.hotListForKey(key);if !ok||h==nil{return errors.New("HOT list sidecar invariant")};p,err:=h.packed();if err!=nil{return err};u:=listPreparedEntry(p);u.expiresAt=sh.expirationAt(key,e);return s.publish(sh,key,u)}
func(s *Store) mutateHotListLocked(h *hotList,fn func()){a:=h.memoryBytes();fn();h.lastMutation=s.now().UnixMilli();s.accountHotListResize(a,h.memoryBytes())}
