package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
	"text/tabwriter"

	"snugkv/internal/server"
)

func main() {
	format := flag.String("format", "markdown", "output format: markdown or json")
	flag.Parse()

	entries := server.CommandInventorySnapshot()
	switch strings.ToLower(*format) {
	case "json":
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		if err := enc.Encode(map[string]any{
			"top_level_command_count": server.TopLevelCommandCount(),
			"entries": entries,
		}); err != nil {
			panic(err)
		}
	case "markdown", "md":
		writeMarkdown(entries)
	default:
		fmt.Fprintf(os.Stderr, "unknown format %q\n", *format)
		os.Exit(2)
	}
}

func writeMarkdown(entries []server.CommandInventoryEntry) {
	top := make([]server.CommandInventoryEntry, 0)
	sub := make([]server.CommandInventoryEntry, 0)
	for _, entry := range entries {
		if entry.Kind == "subcommand" {
			sub = append(sub, entry)
		} else {
			top = append(top, entry)
		}
	}
	sort.Slice(top, func(i, j int) bool { return top[i].Name < top[j].Name })
	sort.Slice(sub, func(i, j int) bool { return sub[i].Name < sub[j].Name })

	fmt.Println("# Implemented Command Inventory")
	fmt.Println()
	fmt.Println("> Generated by `go run ./cmd/commandinventory -format markdown`.")
	fmt.Println("> Do not edit command rows manually.")
	fmt.Println()
	fmt.Printf("- Top-level commands: **%d**\n", len(top))
	fmt.Printf("- Structured subcommands: **%d**\n", len(sub))
	fmt.Println("- Top-level count is the same metadata count used by `COMMAND COUNT`.")
	fmt.Println()
	fmt.Println("## Top-level commands")
	fmt.Println()
	fmt.Println("| Command | Arity | Args | Access | Key mode | Cluster routing | Flags | ACL categories |")
	fmt.Println("|---|---:|---|---|---|---|---|---|")
	for _, e := range top {
		fmt.Printf("| `%s` | %d | %s | %s | %s | %s | %s | %s |\n",
			e.Name,
			e.Arity,
			argRange(e),
			access(e.Write),
			e.KeyMode,
			e.ClusterRouting,
			joinCode(e.Flags),
			joinCode(e.ACLCategories),
		)
	}

	fmt.Println()
	fmt.Println("## Structured subcommands")
	fmt.Println()
	fmt.Println("| Subcommand | Parent | Arity | Access | Flags | ACL categories |")
	fmt.Println("|---|---|---:|---|---|---|")
	for _, e := range sub {
		fmt.Printf("| `%s` | `%s` | %d | %s | %s | %s |\n",
			e.Name,
			e.Parent,
			e.Arity,
			access(e.Write),
			joinCode(e.Flags),
			joinCode(e.ACLCategories),
		)
	}

	fmt.Println()
	fmt.Println("## Interpretation")
	fmt.Println()
	fmt.Println("- `static` key mode means key positions come from the registered command metadata.")
	fmt.Println("- `dynamic` means runtime key discovery is required, such as EVAL/FCALL, SORT, MIGRATE, XREAD, or multi-pop/algebra commands.")
	fmt.Println("- Cluster routing labels describe how the current router treats the command's discovered keys; they are not a claim of exhaustive Redis Cluster parity.")
	fmt.Println("- ACL categories and flags are the metadata exposed by SnugKV's current COMMAND/ACL compatibility layer.")
}

func argRange(e server.CommandInventoryEntry) string {
	if e.MaxArgs == 0 {
		return fmt.Sprintf("%d+", e.MinArgs)
	}
	if e.MinArgs == e.MaxArgs {
		return fmt.Sprintf("%d", e.MinArgs)
	}
	return fmt.Sprintf("%d..%d", e.MinArgs, e.MaxArgs)
}

func access(write bool) string {
	if write {
		return "write"
	}
	return "read/control"
}

func joinCode(values []string) string {
	if len(values) == 0 {
		return "-"
	}
	parts := make([]string, 0, len(values))
	for _, value := range values {
		parts = append(parts, "`"+value+"`")
	}
	return strings.Join(parts, " ")
}

// Keep tabwriter imported in this command's dependency set so future inventory
// formats can add aligned terminal output without changing package wiring.
var _ = tabwriter.NewWriter
