#!/usr/bin/env bash
set -euo pipefail

# Reproducible Redis-vs-SnugKV public baseline suite.
# Compares Redis 8.2 with optimized SnugKV in isolated fresh containers.

KEYS="${KEYS:-1000000}"
GET_OPS="${GET_OPS:-2000000}"
MIXED_OPS="${MIXED_OPS:-1000000}"
TTL_OPS="${TTL_OPS:-1000000}"
WORKERS="${WORKERS:-8}"
PIPELINE="${PIPELINE:-256}"
RUNS="${RUNS:-3}"
SETTLE_MS="${SETTLE_MS:-10000}"
PROFILES="${PROFILES:-counter uuid cache-json text random}"
ROOT_OUT="${ROOT_OUT:-benchmark-results/public-baseline-$(date +%Y%m%d-%H%M%S)}"
SNUG_IMAGE="${SNUG_IMAGE:-snugkv-bench:local}"

dirty="$(git status --porcelain)"
if [[ -n "$dirty" ]]; then
  echo "error: public baseline requires a clean git worktree" >&2
  echo >&2
  echo "dirty paths:" >&2
  printf '%s\n' "$dirty" >&2
  echo >&2
  echo "Commit, stash, remove, or ignore those paths as appropriate, then rerun." >&2
  exit 2
fi

mkdir -p "$ROOT_OUT"

python3 - "$ROOT_OUT/environment.json" "$KEYS" "$GET_OPS" "$MIXED_OPS" "$TTL_OPS" "$WORKERS" "$PIPELINE" "$RUNS" "$SETTLE_MS" "$PROFILES" <<'PY'
import json, os, platform, subprocess, sys

def cmd(*args):
    try:
        return subprocess.check_output(args, text=True, stderr=subprocess.STDOUT).strip()
    except Exception:
        return ""

out = {
    "git_commit": cmd("git", "rev-parse", "HEAD"),
    "git_branch": cmd("git", "rev-parse", "--abbrev-ref", "HEAD"),
    "git_status_porcelain": cmd("git", "status", "--porcelain"),
    "timestamp_utc": cmd("date", "-u", "+%Y-%m-%dT%H:%M:%SZ"),
    "hostname": platform.node(),
    "os": platform.platform(),
    "machine": platform.machine(),
    "python": platform.python_version(),
    "go": cmd("go", "version"),
    "docker": cmd("docker", "--version"),
    "cpus": os.cpu_count(),
    "cpu_model": "",
    "memory_total_bytes": 0,
    "benchmark": {
        "keys": int(sys.argv[2]),
        "get_ops": int(sys.argv[3]),
        "mixed_ops": int(sys.argv[4]),
        "ttl_ops": int(sys.argv[5]),
        "workers": int(sys.argv[6]),
        "pipeline": int(sys.argv[7]),
        "runs": int(sys.argv[8]),
        "settle_ms": int(sys.argv[9]),
        "profiles": sys.argv[10].split(),
        "servers": ["redis", "snug-opt"],
        "workloads": ["load", "get", "mixed", "ttl"],
        "redis_image": "redis:8.2"
    }
}

try:
    with open("/proc/cpuinfo") as f:
        for line in f:
            if line.lower().startswith("model name"):
                out["cpu_model"] = line.split(":",1)[1].strip()
                break
except Exception:
    pass

try:
    out["memory_total_bytes"] = int(os.sysconf("SC_PHYS_PAGES") * os.sysconf("SC_PAGE_SIZE"))
except Exception:
    pass

with open(sys.argv[1], "w") as f:
    json.dump(out, f, indent=2)
PY

echo "Building fresh SnugKV benchmark image..."
docker build -t "$SNUG_IMAGE" .

{
  echo "redis_version=$(docker run --rm redis:8.2 redis-server --version 2>/dev/null || true)"
  echo "snug_image=$SNUG_IMAGE"
  echo "snug_image_id=$(docker image inspect "$SNUG_IMAGE" --format '{{.Id}}' 2>/dev/null || true)"
} > "$ROOT_OUT/server-versions.txt"

for profile in $PROFILES; do
  echo
  echo "################################################################"
  echo "PUBLIC BASELINE PROFILE: $profile"
  echo "################################################################"

  PROFILE="$profile" \
  KEYS="$KEYS" \
  GET_OPS="$GET_OPS" \
  MIXED_OPS="$MIXED_OPS" \
  TTL_OPS="$TTL_OPS" \
  WORKERS="$WORKERS" \
  PIPELINE="$PIPELINE" \
  RUNS="$RUNS" \
  SETTLE_MS="$SETTLE_MS" \
  SERVERS="redis snug-opt" \
  WORKLOADS="load get mixed ttl" \
  ROOT_OUT="$ROOT_OUT/$profile" \
  BUILD_IMAGE=0 \
  SNUG_IMAGE="$SNUG_IMAGE" \
  bash scripts/bench/compare-realistic-workloads.sh
done

python3 - "$ROOT_OUT" <<'PY'
import json, pathlib, sys

root = pathlib.Path(sys.argv[1])
rows = []
for summary_path in sorted(root.glob("*/matrix-summary.json")):
    profile = summary_path.parent.name
    with summary_path.open() as f:
        summary = json.load(f)
    for row in summary:
        row = dict(row)
        row["profile"] = profile
        rows.append(row)

if not rows:
    raise SystemExit("no matrix-summary.json files found")

with (root / "public-summary.json").open("w") as f:
    json.dump(rows, f, indent=2)

by_key = {(r["profile"], r["server"], r["workload"]): r for r in rows}
profiles = sorted({r["profile"] for r in rows})

md = [
    "# Redis 8.2 vs SnugKV public baseline",
    "",
    "Generated by scripts/bench/public-baseline.sh.",
    "",
    "Pipelined LOAD/GET percentiles are amortized per-operation batch times,",
    "not independent one-request latency measurements.",
    "",
    "## Throughput and latency",
    "",
    "| Profile | Workload | Redis ops/s | SnugKV ops/s | Snug/Redis | Redis p95 us | Snug p95 us |",
    "|---|---:|---:|---:|---:|---:|---:|",
]

for profile in profiles:
    for workload in ("load", "get", "mixed", "ttl"):
        rr = by_key.get((profile, "redis", workload))
        sr = by_key.get((profile, "snug_opt", workload))
        if not rr or not sr:
            continue
        rops = rr["ops_per_second_median"]
        sops = sr["ops_per_second_median"]
        ratio = sops / rops if rops else 0
        md.append(
            f"| {profile} | {workload} | {rops:,.0f} | {sops:,.0f} | "
            f"{ratio:.3f}x | {rr['p95_us_median']:.2f} | {sr['p95_us_median']:.2f} |"
        )

md += [
    "",
    "## Memory after load",
    "",
    "| Profile | Redis B/key | SnugKV B/key | Snug vs Redis |",
    "|---|---:|---:|---:|",
]

for profile in profiles:
    rr = by_key.get((profile, "redis", "load"))
    sr = by_key.get((profile, "snug_opt", "load"))
    if not rr or not sr:
        continue
    rb = rr.get("bytes_per_key_delta_median", 0)
    sb = sr.get("bytes_per_key_delta_median", 0)
    pct = ((sb / rb) - 1.0) * 100.0 if rb else 0
    md.append(f"| {profile} | {rb:.2f} | {sb:.2f} | {pct:+.1f}% |")

md += [
    "",
    "## Evidence",
    "",
    "- Raw per-run JSON is retained under each profile directory.",
    "- public-summary.json is the machine-readable aggregate.",
    "- environment.json captures commit, machine and benchmark configuration.",
    "- server-versions.txt captures Redis and SnugKV image identity.",
    "",
    "These measurements are machine/workload specific and must not be represented",
    "as universal Redis-vs-SnugKV performance claims.",
]

(root / "PUBLIC_BASELINE_RESULTS.md").write_text("\n".join(md) + "\n")

print()
print("===== PUBLIC BASELINE COMPLETE =====")
print("summary:", root / "public-summary.json")
print("scoreboard:", root / "PUBLIC_BASELINE_RESULTS.md")
print("environment:", root / "environment.json")
PY

echo
echo "Public baseline artifacts:"
echo "  $ROOT_OUT/environment.json"
echo "  $ROOT_OUT/server-versions.txt"
echo "  $ROOT_OUT/public-summary.json"
echo "  $ROOT_OUT/PUBLIC_BASELINE_RESULTS.md"
